---
title: "Andre Oliveira de Carvalho e Silva"
image: 514004953_2911904128989138_2538718504871531387_n (2).jpg
about: 
  template: jolla
  links: 
    - icon: linkedin
      text: Linkedin
      href: https://www.linkedin.com/in/andr%C3%A9-oliveira-de-carvalho-e-silva-13b015393/
    - icon: github
      text: Github
      href: https://github.com/andredecarvalhosilva-coder
---

Sou uma pessoa extremamente sociável, criativa e determinada, com grande paixão por esportes e pela busca constante de novos desafios. Atualmente curso Ciências Exatas na UFJF, onde iniciei meus estudos em 2024, e venho desenvolvendo habilidades em Python e C++, além de aprimorar minha lógica, comunicação e proatividade.

Tenho uma trajetória marcada pela dedicação e disciplina: fui Campeão Brasileiro de Judô e conquistei medalha de bronze no Campeonato Mineiro de Xadrez, experiências que moldaram minha capacidade de foco, estratégia e resiliência.

Meu objetivo é crescer profissionalmente, aprender o máximo possível com a empresa e contribuir com responsabilidade, criatividade e vontade de evoluir. Sonho em viajar o mundo, viver novas experiências e conhecer pessoas de diferentes culturas, ampliando minhas perspectivas pessoais e profissionais.

📧 andreoliveiradecarvalhoesilva\@gmail.com
